import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

test('index.html exposes Setup and Call tabs without a visible debug surface', () => {
  const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');

  assert.match(html, /id="screen-tab-setup"/);
  assert.match(html, /data-screen-target="setup"/);
  assert.match(html, /id="screen-setup"/);
  assert.match(html, /data-screen="setup"/);
  assert.match(html, /id="screen-tab-call"/);
  assert.match(html, /data-screen-target="call"/);
  assert.match(html, /id="screen-call"/);
  assert.match(html, /data-screen="call"/);
  assert.match(html, /<article class="call-panel">/);
  assert.match(html, /id="setup-avatar-host"/);
  assert.match(html, /id="call-avatar-host"/);
  assert.match(html, /id="avatar-preview-shell"/);
  assert.doesNotMatch(html, /class="preview-head"/);
  assert.match(html, /id="preview-character-animation"/);
  assert.match(html, /id="preview-voice-sample"/);
  assert.match(html, /id="preview-voice-sample-timer"/);
  assert.match(html, /id="camera-distance-input"/);
  assert.match(html, /max="2"/);
  assert.match(html, /id="camera-distance-value"/);
  assert.match(html, /id="call-layout"/);
  assert.match(html, /class="call-stage"/);
  assert.match(html, /id="call-mic-toggle"/);
  assert.match(html, /class="call-mic-toggle"/);
  assert.match(html, /class="call-mic-icon call-mic-icon--live"/);
  assert.match(html, /class="call-mic-icon call-mic-icon--muted"/);
  assert.match(html, /id="call-empty-state"/);
  assert.match(html, /id="call-empty-state-title"/);
  assert.match(html, /id="call-empty-state-detail"/);
  assert.match(html, /id="call-stage-loading"/);
  assert.match(html, /id="call-stage-loading-label"/);
  assert.match(html, /id="call-stage-loading-countdown"/);
  assert.match(html, /id="call-stage-loading-tip"/);
  assert.match(html, /class="call-stage-loading-card"/);
  assert.match(html, /id="call-self-view"/);
  assert.match(html, /id="call-self-video"/);
  assert.match(html, /id="call-self-status"/);
  assert.match(html, /class="call-self-controls"/);
  assert.match(html, /id="call-camera-toggle"/);
  assert.match(html, /id="call-speaker-toggle"/);
  assert.match(html, /id="call-history-toggle"/);
  assert.match(html, /id="call-mic-toggle"/);
  assert.match(html, /id="join-call"/);
  assert.match(html, /id="call-subtitle-overlay"/);
  assert.match(html, /id="call-subtitle-human"/);
  assert.match(html, /id="call-subtitle-agent"/);
  assert.match(html, /id="call-thinking-timer"/);
  assert.match(html, /id="call-deferred-indicator"/);
  assert.match(html, /id="call-deferred-list"/);
  assert.match(html, /id="call-history-panel"/);
  assert.match(html, /id="call-history-list"/);
  assert.match(html, /class="call-controls-stack"/);
  assert.match(html, /class="call-action-bar"/);
  assert.match(html, /class="call-input-panel"/);
  assert.match(html, /id="typed-input"/);
  assert.match(html, /id="send-typed"/);
  assert.match(html, /class="call-compose call-compose--dock"/);
  assert.match(html, /class="call-action-button call-action-button--danger"/);
  assert.doesNotMatch(html, /<h2>Agent<\/h2>/);
  assert.doesNotMatch(html, /id="active-avatar"/);
  assert.doesNotMatch(html, /id="active-emote"/);
  assert.doesNotMatch(html, /id="active-gesture"/);
  assert.doesNotMatch(html, /id="active-mouth"/);
  assert.match(html, /class="voice-sample-picker"/);
  assert.match(html, /class="voice-sample-input"/);
  assert.match(html, /id="continuity-settings-open"/);
  assert.match(html, /id="plugin-settings-open"/);
  assert.match(html, /id="advanced-settings-open"/);
  assert.match(html, /id="continuity-settings-dialog"/);
  assert.ok(
    html.indexOf('id="continuity-settings-dialog"') <
      html.indexOf('id="manual-workspace-root"'),
  );
  assert.match(html, /id="manual-workspace-root-select"/);
  assert.match(html, /id="plugin-settings-dialog"/);
  assert.match(html, /id="advanced-settings-dialog"/);
  assert.match(html, /id="continuity-settings-close"/);
  assert.match(html, /id="continuity-settings-save"/);
  assert.match(html, /id="continuity-settings-dirty"/);
  assert.match(html, /id="plugin-settings-close"/);
  assert.match(html, /id="plugin-settings-save"/);
  assert.match(html, /id="codex-plugin-list"/);
  assert.match(html, /id="advanced-settings-close"/);
  assert.match(html, /id="advanced-settings-save"/);
  assert.match(html, /id="advanced-control-computer"/);
  assert.match(html, /id="advanced-complex-tasks"/);
  assert.match(html, /class="continuity-trigger"/);
  assert.match(html, /class="prompt-dialog-card continuity-dialog-card"/);
  assert.doesNotMatch(html, /id="voice-sample-detail"/);
  assert.doesNotMatch(html, /Voice Sample \(WAV\)/);
  assert.doesNotMatch(html, /id="launch-mode-chip"/);
  assert.doesNotMatch(html, /id="workspace-chip"/);
  assert.doesNotMatch(html, /id="hero-title"/);
  assert.doesNotMatch(html, /id="call-title"/);
  assert.doesNotMatch(html, /id="call-subtitle"/);
  assert.doesNotMatch(html, /id="call-agent-name"/);
  assert.doesNotMatch(html, /id="call-action-detail"/);
  assert.doesNotMatch(html, /class="subtitle-stack"/);
  assert.doesNotMatch(html, /class="call-footer"/);
  assert.doesNotMatch(html, /Recognition/);
  assert.doesNotMatch(html, /Transcript Preview/);
  assert.doesNotMatch(html, /Set up your agent/);
  assert.doesNotMatch(html, /Agent Presence/);
  assert.doesNotMatch(html, /Codex OpenAI/);
  assert.doesNotMatch(html, /<header class="hero panel">/);
  assert.doesNotMatch(html, /class="setup-control setup-control--agent-self"/);
  assert.match(html, /class="floating-mode-switch"/);
  assert.match(html, /class="screen-nav screen-nav--floating"/);
  assert.match(html, /class="screen-tab-icon"/);
  assert.match(html, /class="screen-tab-label"/);
  assert.doesNotMatch(html, /class="status-strip status-strip--debug"/);
  assert.doesNotMatch(html, /<details class="panel debug-panel">/);
  assert.doesNotMatch(html, /id="screen-tab-agent-setup"/);
});

test('screen navigator recognizes the setup and call screen ids', () => {
  const source = readFileSync(new URL('./screens.js', import.meta.url), 'utf8');

  assert.match(source, /new Set\(\['setup', 'call'\]\)/);
});

test('styles keep the floating mode switch compact', () => {
  const css = readFileSync(new URL('../styles.css', import.meta.url), 'utf8');

  assert.match(css, /\[hidden\]\s*\{[\s\S]*display:\s*none\s*!important;/);
  assert.match(css, /html,\s*body\s*\{[\s\S]*height:\s*100%;/);
  assert.match(css, /body\s*\{[\s\S]*min-height:\s*100dvh;[\s\S]*overflow:\s*hidden;/);
  assert.match(css, /\.shell\s*\{[\s\S]*width:\s*100vw;[\s\S]*min-height:\s*100dvh;[\s\S]*padding:\s*0;[\s\S]*overflow:\s*hidden;/);
  assert.match(css, /\.floating-mode-switch\s*\{[\s\S]*position:\s*fixed;[\s\S]*top:\s*18px;[\s\S]*left:\s*18px;/);
  assert.match(css, /\.screen-nav--floating\s*\{[\s\S]*gap:\s*4px;[\s\S]*padding:\s*4px;/);
  assert.match(css, /\.setup-control--continuity\s*\{[\s\S]*grid-column:\s*1 \/ -1;/);
  assert.match(css, /\.setup-settings-actions\s*\{[\s\S]*display:\s*flex;/);
  assert.match(css, /\.continuity-trigger\s*\{[\s\S]*min-height:\s*48px;/);
  assert.match(css, /\.continuity-dialog-card\s*\{[\s\S]*width:\s*min\(720px,\s*calc\(100vw - 24px\)\);/);
  assert.match(css, /\.continuity-dialog-actions\s*\{[\s\S]*justify-content:\s*flex-end;/);
  assert.match(css, /\.continuity-save-button\s*\{[\s\S]*min-width:\s*112px;/);
  assert.match(css, /\.plugin-settings-list,\s*\.advanced-settings-list\s*\{/);
  assert.match(css, /\.plugin-setting-card,\s*\.advanced-setting-card\s*\{/);
  assert.match(css, /\.screen\[data-screen='setup'\]\s*\{[\s\S]*height:\s*100dvh;[\s\S]*padding:\s*24px 24px 32px;[\s\S]*overflow-y:\s*auto;[\s\S]*overscroll-behavior:\s*contain;/);
  assert.match(css, /\.screen-tab\s*\{[\s\S]*min-width:\s*0;[\s\S]*min-height:\s*40px;/);
  assert.match(css, /\.screen-tab-icon\s*\{[\s\S]*width:\s*14px;/);
  assert.match(css, /\.call-stage-loading\s*\{[\s\S]*position:\s*absolute;/);
  assert.match(css, /\.call-stage-loading-card\s*\{[\s\S]*border-radius:\s*30px;/);
  assert.match(css, /\.call-stage-loading-countdown\s*\{[\s\S]*font-family:\s*var\(--mono\)/);
  assert.match(css, /\.call-stage-loading-tip\s*\{[\s\S]*line-height:\s*1\.55;/);
  assert.match(css, /@keyframes call-stage-spin\s*\{/);
  assert.match(css, /\.call-controls-stack\s*\{[\s\S]*position:\s*absolute;[\s\S]*bottom:/);
  assert.match(css, /\.call-deferred-indicator\s*\{[\s\S]*position:\s*absolute;[\s\S]*left:/);
  assert.match(css, /\.call-deferred-list\s*\{[\s\S]*display:\s*grid;/);
  assert.match(css, /\.call-deferred-item\s*\{[\s\S]*display:\s*inline-flex;/);
  assert.match(css, /\.call-deferred-dot\s*\{[\s\S]*animation:\s*call-deferred-beat/);
  assert.match(css, /\.call-deferred-label\s*\{[\s\S]*font-weight:\s*600;/);
  assert.match(css, /\.call-deferred-detail\s*\{[\s\S]*font-size:\s*0\.72rem;/);
  assert.match(css, /\.call-deferred-time\s*\{[\s\S]*font-family:\s*var\(--mono\)/);
  assert.match(css, /\.call-action-bar\s*\{[\s\S]*display:\s*flex;[\s\S]*justify-content:\s*center;/);
  assert.match(css, /\.call-action-button\s*\{[\s\S]*border-radius:\s*999px;[\s\S]*background:\s*rgba?\(/);
  assert.match(css, /#join-call\[data-mode='start-call'\]\s*\{[\s\S]*#63dc8d[\s\S]*#1fb86b/);
  assert.match(css, /\.call-action-button--danger\s*\{[\s\S]*background:[\s\S]*rgba?\(/);
  assert.match(css, /\.call-self-cluster\s*\{[\s\S]*position:\s*absolute;[\s\S]*bottom:\s*clamp\(248px,\s*26vh,\s*324px\);/);
  assert.match(css, /\.call-self-view\s*\{[\s\S]*position:\s*relative;[\s\S]*width:\s*100%;/);
  assert.match(css, /\.call-self-controls\s*\{[\s\S]*position:\s*absolute;[\s\S]*top:\s*100%;[\s\S]*transform:\s*translate\(-50%,\s*-30%\)/);
  assert.match(css, /\.call-self-video\s*\{[\s\S]*width:\s*100%;[\s\S]*height:\s*100%;/);
  assert.match(css, /\.call-subtitle-overlay\s*\{[\s\S]*display:\s*grid;[\s\S]*justify-items:\s*center;/);
  assert.match(css, /\.call-subtitle-chip\s*\{[\s\S]*border-radius:\s*999px;/);
  assert.match(css, /\.call-compose--dock\s*\{[\s\S]*width:\s*min\(/);
  assert.match(css, /\.call-mic-toggle\[data-state='live'\]\[data-listening='true'\]\s*\{/);
  assert.match(css, /\.call-mic-toggle\[data-state='live'\]\[data-speaking='true'\]\s*\{[\s\S]*var\(--mic-glow\)/);
  assert.match(css, /@keyframes call-deferred-beat\s*\{/);
  assert.match(css, /\.call-layout\[data-history-visible='true'\]\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s*320px;/);
  assert.match(css, /\.call-layout\[data-history-visible='true'\]\[data-history-collapsed='true'\]\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\);/);
  assert.match(css, /\.call-history\[data-collapsed='true'\]\s+\.call-history-list\s*\{[\s\S]*display:\s*none;/);
  assert.match(css, /\.call-history\s*\{[\s\S]*padding:\s*12px 14px 14px;/);
  assert.match(css, /\.call-panel\s*\{[\s\S]*background:\s*transparent;[\s\S]*border:\s*none;/);
  assert.match(css, /\.screen\[data-screen='call'\]\s*\{[\s\S]*width:\s*100vw;[\s\S]*min-height:\s*100dvh;[\s\S]*overflow:\s*hidden;/);
  assert.match(css, /\.call-panel\s*\{[\s\S]*min-height:\s*100dvh;[\s\S]*padding:\s*0;/);
  assert.match(css, /\.avatar-host--call\s*\{[\s\S]*position:\s*relative;[\s\S]*min-height:\s*100dvh;/);
  assert.match(css, /\.avatar-host--call\s+\.stage-shell,\s*\.avatar-host--call\s+#agent-canvas\s*\{[\s\S]*height:\s*100dvh;[\s\S]*border-radius:\s*0;/);
  assert.match(css, /\.avatar-host--call\[data-agent-online='false'\]\s*\{[\s\S]*linear-gradient\(180deg,\s*rgba\(17,\s*27,\s*44,\s*0\.92\),\s*rgba\(7,\s*13,\s*24,\s*0\.94\)\);/);
  assert.match(css, /\.avatar-host--call\[data-agent-online='false'\]\s*\{[\s\S]*border-radius:\s*0;/);
  assert.match(css, /\.call-empty-state\s*\{[\s\S]*position:\s*absolute;[\s\S]*place-content:\s*center;/);
  assert.match(css, /\.call-stage\s*\{[\s\S]*display:\s*grid;[\s\S]*min-height:\s*100dvh;/);
  assert.match(css, /\.call-stage-loading\s*\{[\s\S]*position:\s*absolute;[\s\S]*border-radius:\s*0;/);
  assert.match(css, /\.call-compose\s*\{[\s\S]*display:\s*flex;/);
  assert.match(css, /\.call-compose-input\s*\{[\s\S]*min-height:\s*42px;/);
  assert.match(css, /\.turn-item\s*\{[\s\S]*max-width:\s*88%;[\s\S]*padding:\s*10px 12px;/);
  assert.match(css, /\.turn-item\[data-role='human'\]\s*\{[\s\S]*justify-self:\s*end;/);
  assert.match(css, /\.turn-item\[data-role='agent'\]\s*\{[\s\S]*justify-self:\s*start;/);
  assert.match(css, /\.avatar-preview-shell\s*\{[\s\S]*transition:[\s\S]*opacity 260ms ease/);
  assert.match(css, /\.avatar-host--call\[data-agent-online='false'\]\s+\.avatar-preview-shell\s*\{[\s\S]*opacity:\s*1;[\s\S]*brightness\(0\.44\);/);
});
