import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

test('index.html exposes Setup and Call tabs without a visible debug surface', () => {
  const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');

  assert.match(html, /id="screen-tab-setup"/);
  assert.match(html, /data-screen-target="setup"/);
  assert.match(html, /id="screen-setup"/);
  assert.match(html, /data-screen="setup"/);
  assert.match(html, /id="screen-tab-call"/);
  assert.match(html, /data-screen-target="call"/);
  assert.match(html, /id="screen-call"/);
  assert.match(html, /data-screen="call"/);
  assert.match(html, /<article class="call-panel">/);
  assert.match(html, /id="setup-avatar-host"/);
  assert.match(html, /id="call-avatar-host"/);
  assert.match(html, /id="avatar-preview-shell"/);
  assert.doesNotMatch(html, /class="preview-head"/);
  assert.match(html, /id="preview-character-animation"/);
  assert.match(html, /id="preview-voice-sample"/);
  assert.match(html, /id="preview-voice-sample-timer"/);
  assert.match(html, /id="call-layout"/);
  assert.match(html, /class="call-stage"/);
  assert.match(html, /id="call-mic-toggle"/);
  assert.match(html, /class="call-mic-toggle"/);
  assert.match(html, /class="call-mic-icon call-mic-icon--live"/);
  assert.match(html, /class="call-mic-icon call-mic-icon--muted"/);
  assert.match(html, /id="call-empty-state"/);
  assert.match(html, /id="call-empty-state-title"/);
  assert.match(html, /id="call-empty-state-detail"/);
  assert.match(html, /id="call-stage-loading"/);
  assert.match(html, /id="call-subtitle-combined"/);
  assert.match(html, /id="call-thinking-timer"/);
  assert.match(html, /id="call-history-panel"/);
  assert.match(html, /id="call-history-list"/);
  assert.match(html, /id="call-history-toggle"/);
  assert.match(html, /class="call-history-toggle call-history-toggle--overlay"/);
  assert.match(html, /class="call-subtitle-bar"/);
  assert.match(html, /class="primary call-button call-button--overlay"/);
  assert.match(html, /id="typed-input"/);
  assert.match(html, /id="send-typed"/);
  assert.match(html, /class="call-compose"/);
  assert.match(html, /class="call-button-icon call-button-icon--start"/);
  assert.match(html, /class="call-button-icon call-button-icon--end"/);
  assert.doesNotMatch(html, /<h2>Agent<\/h2>/);
  assert.doesNotMatch(html, /id="active-avatar"/);
  assert.doesNotMatch(html, /id="active-emote"/);
  assert.doesNotMatch(html, /id="active-gesture"/);
  assert.doesNotMatch(html, /id="active-mouth"/);
  assert.match(html, /class="voice-sample-picker"/);
  assert.match(html, /class="voice-sample-input"/);
  assert.doesNotMatch(html, /id="voice-sample-detail"/);
  assert.doesNotMatch(html, /Voice Sample \(WAV\)/);
  assert.doesNotMatch(html, /id="launch-mode-chip"/);
  assert.doesNotMatch(html, /id="workspace-chip"/);
  assert.doesNotMatch(html, /id="hero-title"/);
  assert.doesNotMatch(html, /id="call-title"/);
  assert.doesNotMatch(html, /id="call-subtitle"/);
  assert.doesNotMatch(html, /id="call-agent-name"/);
  assert.doesNotMatch(html, /id="call-action-detail"/);
  assert.doesNotMatch(html, /class="subtitle-stack"/);
  assert.doesNotMatch(html, /class="call-footer"/);
  assert.doesNotMatch(html, /Recognition/);
  assert.doesNotMatch(html, /Transcript Preview/);
  assert.doesNotMatch(html, /Set up your agent/);
  assert.doesNotMatch(html, /Agent Presence/);
  assert.doesNotMatch(html, /Codex OpenAI/);
  assert.doesNotMatch(html, /<header class="hero panel">/);
  assert.match(html, /class="floating-mode-switch"/);
  assert.match(html, /class="screen-nav screen-nav--floating"/);
  assert.match(html, /class="screen-tab-icon"/);
  assert.match(html, /class="screen-tab-label"/);
  assert.doesNotMatch(html, /class="status-strip status-strip--debug"/);
  assert.doesNotMatch(html, /<details class="panel debug-panel">/);
  assert.doesNotMatch(html, /id="screen-tab-agent-setup"/);
});

test('screen navigator recognizes the setup and call screen ids', () => {
  const source = readFileSync(new URL('./screens.js', import.meta.url), 'utf8');

  assert.match(source, /new Set\(\['setup', 'call'\]\)/);
});

test('styles keep the floating mode switch compact', () => {
  const css = readFileSync(new URL('../styles.css', import.meta.url), 'utf8');

  assert.match(css, /\[hidden\]\s*\{[\s\S]*display:\s*none\s*!important;/);
  assert.match(css, /\.floating-mode-switch\s*\{[\s\S]*position:\s*absolute;/);
  assert.match(css, /\.screen-nav--floating\s*\{[\s\S]*gap:\s*4px;[\s\S]*padding:\s*4px;/);
  assert.match(css, /\.screen-tab\s*\{[\s\S]*min-width:\s*0;[\s\S]*min-height:\s*40px;/);
  assert.match(css, /\.screen-tab-icon\s*\{[\s\S]*width:\s*14px;/);
  assert.match(css, /\.call-button--overlay\s*\{[\s\S]*width:\s*44px;/);
  assert.match(css, /\.call-button\[data-mode='end-call'\]\s*\{[\s\S]*color:\s*#ffffff;/);
  assert.match(css, /\.call-stage-loading\s*\{[\s\S]*position:\s*absolute;/);
  assert.match(css, /\.call-mic-toggle\s*\{[\s\S]*position:\s*absolute;[\s\S]*width:\s*42px;/);
  assert.match(css, /\.call-mic-toggle\[data-state='live'\]\[data-speaking='true'\]\s*\{[\s\S]*var\(--mic-glow\)/);
  assert.match(css, /\.call-layout\[data-history-visible='true'\]\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s*320px;/);
  assert.match(css, /\.call-layout\[data-history-visible='true'\]\[data-history-collapsed='true'\]\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\);/);
  assert.match(css, /\.call-history\[data-collapsed='true'\]\s+\.call-history-list\s*\{[\s\S]*display:\s*none;/);
  assert.match(css, /\.call-history-toggle--overlay\s*\{[\s\S]*flex:\s*0 0 36px;/);
  assert.match(css, /\.call-panel\s*\{[\s\S]*background:\s*transparent;[\s\S]*border:\s*none;/);
  assert.match(css, /\.avatar-host--call\s*\{[\s\S]*position:\s*relative;[\s\S]*min-height:\s*420px;/);
  assert.match(css, /\.avatar-host--call\[data-agent-online='false'\]\s*\{[\s\S]*linear-gradient\(180deg,\s*rgba\(17,\s*27,\s*44,\s*0\.92\),\s*rgba\(7,\s*13,\s*24,\s*0\.94\)\);/);
  assert.match(css, /\.call-empty-state\s*\{[\s\S]*position:\s*absolute;[\s\S]*place-content:\s*center;/);
  assert.match(css, /\.call-stage\s*\{[\s\S]*display:\s*grid;[\s\S]*gap:\s*10px;/);
  assert.match(css, /\.call-subtitle-overlay\s*\{[\s\S]*position:\s*relative;[\s\S]*background:\s*rgba\(255,\s*255,\s*255,\s*0\.65\);/);
  assert.match(css, /\.call-compose\s*\{[\s\S]*display:\s*flex;/);
  assert.match(css, /\.call-compose-input\s*\{[\s\S]*min-height:\s*42px;/);
  assert.match(css, /\.turn-item\s*\{[\s\S]*max-width:\s*88%;[\s\S]*padding:\s*10px 12px;/);
  assert.match(css, /\.turn-item\[data-role='human'\]\s*\{[\s\S]*justify-self:\s*end;/);
  assert.match(css, /\.turn-item\[data-role='agent'\]\s*\{[\s\S]*justify-self:\s*start;/);
  assert.match(css, /\.avatar-preview-shell\s*\{[\s\S]*transition:[\s\S]*opacity 260ms ease/);
  assert.match(css, /\.avatar-host--call\[data-agent-online='false'\]\s+\.avatar-preview-shell\s*\{[\s\S]*opacity:\s*1;[\s\S]*brightness\(0\.44\);/);
});
